pipeline {
    agent any

    environment {
        DOCKER_BACKEND = "akrana2006/backend:latest"
        DOCKER_FRONTEND = "akrana2006/frontend:latest"
    }

    stages {

        stage('Checkout') {
            steps {
                git credentialsId: 'github-creds',
                    url: 'https://github.com/itsakrana/gitops-devops-dashboard.git',
                    branch: 'master'
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    '''
                }
            }
        }

        stage('Build Backend Image') {
            steps {
                sh '''
                docker build -t $DOCKER_BACKEND ./backend
                '''
            }
        }

        stage('Build Frontend Image') {
            steps {
                sh '''
                docker build -t $DOCKER_FRONTEND ./frontend
                '''
            }
        }

        stage('Push Backend Image') {
            steps {
                sh '''
                docker push $DOCKER_BACKEND
                '''
            }
        }

        stage('Push Frontend Image') {
            steps {
                sh '''
                docker push $DOCKER_FRONTEND
                '''
            }
        }

        stage('Deploy Status') {
            steps {
                echo "✅ Images pushed: backend & frontend (latest)"
            }
        }
    }
}
