pipeline {
  agent any

  environment {
    DOCKER_USER = "akrana2006"
    DOCKER_PASS = credentials('docker-pass')
  }

  stages {

    stage('Checkout') {
      steps {
        git 'https://github.com/itsakrana/gitops-devops-dashboard.git'
      }
    }

    stage('Docker Login') {
      steps {
        sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
      }
    }

    stage('Build Images') {
      steps {
        sh "docker build -t $DOCKER_USER/backend:latest ./backend"
        sh "docker build -t $DOCKER_USER/frontend:latest ./frontend"
      }
    }

    stage('Push Images') {
      steps {
        sh "docker push $DOCKER_USER/backend:latest"
        sh "docker push $DOCKER_USER/frontend:latest"
      }
    }

    stage('Deploy Status') {
      steps {
        echo "🚀 Deployment Pipeline Completed"
      }
    }
  }
}
